name: WWW / Deno Deploy

on:
  release:
    types: [published]
  
  push:
    branches: [main]
    paths:
      - 'examples/ultra-website/**'

jobs:
  deploy:
    name: WWW / Deno Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./examples/ultra-website
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build site
        run: deno run -A ./build.ts

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: ultra-docs
          entrypoint: server.js
          root: examples/ultra-website/.ultra
          import-map: importMap.server.json